import Foundation

// Held-out labeled fixture for Catch Up evaluation. Authored independently of the filter.
// Own messages (own = true) are labeled signal = false: the owner does not need a summary of their own words.
enum CatchUpHeldOut {
    static let owner = "Riley Morgan"

    struct Item {
        let chatID: String
        let id: String
        let sender: String
        let ageHours: Double
        let text: String
        let signal: Bool
        let keys: String
        var mention: String? = nil
        var own = false
    }

    static let chats: [(id: String, name: String)] = [
        (id: "c1", name: "Project Halyard"),
        (id: "c2", name: "Sven Lindgren"),
        (id: "c3", name: "Platform Guild"),
        (id: "c4", name: "Office Social"),
        (id: "c5", name: "Incident: Ledgerflow Degradation"),
        (id: "c6", name: "Quillfeather Migration"),
    ]

    private static func m(_ c: String, _ id: String, _ s: String, _ a: Double, _ t: String, _ sig: Bool, _ k: String, mention: String? = nil, own: Bool = false) -> Item {
        Item(chatID: c, id: id, sender: s, ageHours: a, text: t, signal: sig, keys: k, mention: mention, own: own)
    }

    static let items: [Item] = [
        // ---- c1 Project Halyard (project group) ----
        m("c1", "c1-01", "Hannah Weiss", 400, "@Riley Morgan Halyard sign-off checklist is due to procurement by month end, can you own the vendor form?", true, "sign-off checklist|vendor form", mention: "you"),
        m("c1", "c1-02", "Marcus Doyle", 350, "Pilot cohort for Halyard was pushed to the Tamarind release, so nothing ships before then.", true, "Tamarind release|pilot cohort"),
        m("c1", "c1-03", "Fiona Gallagher", 200, "Who wants to put in a lunch order? Going to the Thai place, ordering at noon.", false, "Thai place|lunch order"),
        m("c1", "c1-04", "Marcus Doyle", 199, "Pad see ew for me please", false, "pad see ew"),
        m("c1", "c1-05", "Hannah Weiss", 150, "Decision from the steering call: Halyard drops the Saffron dashboard from phase one, we ship the Juniper exports first.", true, "Saffron dashboard|phase one"),
        m("c1", "c1-06", "Marcus Doyle", 148, "Great news, thanks Hannah!", false, "great news"),
        m("c1", "c1-07", "Fiona Gallagher", 100, "Anyone free right now for a quick call about the Copperfield mockups?", false, "Copperfield mockups|quick call"),
        m("c1", "c1-08", "Hannah Weiss", 96, "@Riley Morgan the Willowbank legal review needs your comments by Friday 5pm or the contract slips a week.", true, "Willowbank", mention: "you"),
        m("c1", "c1-09", "Riley Morgan", 95, "On it, I will get my comments in by Thursday night.", false, "comments in by Thursday", own: true),
        m("c1", "c1-10", "Erik Johansson", 70, "Reminder that the Halyard staging freeze starts Monday the 6th, nothing merges after Friday noon.", true, "staging freeze"),
        m("c1", "c1-11", "Fiona Gallagher", 68, "happy birthday Erik!! 🎂🎉", false, "happy birthday"),
        m("c1", "c1-12", "Marcus Doyle", 66, "Thanks everyone 🙏", false, "thanks everyone"),
        m("c1", "c1-13", "Erik Johansson", 60, "Blocked: the Larkspur API token expired and I can not run the nightly import. Does anyone know who renews it?", true, "Larkspur API token|nightly import"),
        m("c1", "c1-14", "Hannah Weiss", 55, "Petra owns token renewals, I pinged her, should be sorted by tomorrow morning.", true, "token renewals|pinged her"),
        m("c1", "c1-15", "Marcus Doyle", 50, "lol", false, "lol"),
        m("c1", "c1-16", "Petra Nilsson", 40, "@everyone Halyard demo moved from Wednesday 2pm to Thursday 10am, new room link is https://example.com/rooms/halyard-demo", true, "demo moved|halyard-demo", mention: "everyone"),
        m("c1", "c1-17", "Fiona Gallagher", 38, "👍", false, "thumbs up"),
        m("c1", "c1-18", "Hannah Weiss", 30, "@Riley Morgan can you send the Juniper exports schema to Erik before Monday? He is waiting on it.", true, "exports schema|schema to Erik", mention: "you"),
        m("c1", "c1-19", "Riley Morgan", 28, "Sending the schema this afternoon.", false, "sending the schema", own: true),
        m("c1", "c1-20", "Erik Johansson", 20, "Coffee run in 10, who is in? ☕", false, "coffee run"),
        m("c1", "c1-21", "Marcus Doyle", 18, "Coffee chat about the Halyard roadmap? jk, just coffee, oatmilk flat white for me", false, "oatmilk flat white|coffee chat"),
        m("c1", "c1-22", "Hannah Weiss", 10, "Team lunch Thursday is now the mandatory quarterly planning session, bring your OKRs and the Halyard risk register.", true, "quarterly planning|OKRs"),
        m("c1", "c1-23", "Petra Nilsson", 6, "@everyone cake in the kitchen, come grab a slice!", false, "cake in the kitchen|slice", mention: "everyone"),
        m("c1", "c1-24", "Erik Johansson", 3, "Uploaded the Halyard cutover runbook v3 to https://example.com/docs/cutover-runbook-v3 - please read it before the dry run tomorrow.", true, "cutover runbook|dry run"),

        // ---- c2 Sven Lindgren (1:1) ----
        m("c2", "c2-01", "Sven Lindgren", 500, "Riley, the Tundra audit report is finalized, please forward it to compliance by the 15th.", true, "Tundra audit"),
        m("c2", "c2-02", "Sven Lindgren", 460, "Morning! Hope your weekend was good.", false, "hope your weekend"),
        m("c2", "c2-03", "Riley Morgan", 300, "Will do, forwarding it now.", false, "forwarding it now", own: true),
        m("c2", "c2-04", "Sven Lindgren", 230, "Lunch today? I am getting a burrito bowl from the truck if you want one", false, "burrito bowl"),
        m("c2", "c2-05", "Riley Morgan", 229, "yes, chicken please", false, "chicken please", own: true),
        m("c2", "c2-06", "Sven Lindgren", 140, "Are you free right now? Need two minutes on the Obsidian refund policy.", false, "two minutes|free right now"),
        m("c2", "c2-07", "Sven Lindgren", 118, "Actual ask: I need your written sign-off on the Obsidian refund policy by next Wednesday, legal wants it filed.", true, "written sign-off|legal wants"),
        m("c2", "c2-08", "Riley Morgan", 117, "Will do, Wednesday works.", false, "Wednesday works", own: true),
        m("c2", "c2-09", "Sven Lindgren", 90, "thanks!", false, "thanks"),
        m("c2", "c2-10", "Sven Lindgren", 75, "The Pemberton vendor called, they can only deliver the pallets on the 14th now, not the 9th. Plan changed, adjust your schedule.", true, "Pemberton"),
        m("c2", "c2-11", "Sven Lindgren", 52, "Btw the Eastgate offsite is a go, dates are 21st to 23rd, budget approved up to 4k, you are organizing the agenda.", true, "Eastgate offsite"),
        m("c2", "c2-12", "Sven Lindgren", 47, "😂😂😂", false, "laughing emoji"),
        m("c2", "c2-13", "Sven Lindgren", 30, "Do you know if the Fernwood license renewal went through? Finance says the deadline is tomorrow and it is still red.", true, "Fernwood license|license renewal"),
        m("c2", "c2-14", "Riley Morgan", 29, "Checking with finance now.", false, "checking with finance", own: true),
        m("c2", "c2-15", "Sven Lindgren", 20, "We should get a coffee next week, I want to hear about the new place you moved to.", false, "get a coffee|new place"),
        m("c2", "c2-16", "Sven Lindgren", 14, "@Riley Morgan Finance needs the PO number for Fernwood by Monday 9am at the latest, otherwise the renewal lapses. Sending you the form.", true, "PO number", mention: "you"),
        m("c2", "c2-17", "Sven Lindgren", 8, "Also: the Kestrel postmortem doc is at https://example.com/docs/kestrel-postmortem, please add your section.", true, "Kestrel postmortem"),
        m("c2", "c2-18", "Sven Lindgren", 4, "Have a good evening 🙂", false, "good evening"),
        m("c2", "c2-19", "Sven Lindgren", 2, "Quick one: coffee chat about the Zephyr roadmap? jk, just coffee tomorrow at 9?", false, "Zephyr roadmap|coffee tomorrow"),
        m("c2", "c2-20", "Sven Lindgren", 600, "Riley, the annual security training must be completed by the 30th.", true, "security training"),

        // ---- c3 Platform Guild (channel-like) ----
        m("c3", "c3-01", "Ingrid Solberg", 420, "@everyone Platform Guild all-hands moved to the 3rd, agenda will follow.", true, "all-hands moved", mention: "everyone"),
        m("c3", "c3-02", "Declan Murphy", 380, "New hire Aoife starts Monday, please welcome her!", false, "Aoife"),
        m("c3", "c3-03", "Ingrid Solberg", 235, "Weekly reminder: pizza Friday is sponsored by the guild fund, order by 11.", false, "pizza Friday"),
        m("c3", "c3-04", "Declan Murphy", 200, "Two large pepperoni and a margherita for our pod", false, "pepperoni|margherita"),
        m("c3", "c3-05", "Ingrid Solberg", 170, "Design doc for the Basalt cache layer is up for review at https://example.com/docs/basalt-cache, comments due next Tuesday.", true, "cache layer|design doc"),
        m("c3", "c3-06", "Declan Murphy", 160, "Left a few comments 👍", false, "left a few comments"),
        m("c3", "c3-07", "Joanna Wright", 150, "Decision: we are standardizing on the Cobalt linter config across all repos, opt-out requires guild approval.", true, "Cobalt linter"),
        m("c3", "c3-08", "Ingrid Solberg", 130, "@Riley Morgan your team's Basalt migration ticket is the only one still open for the rollout, can you confirm an ETA?", true, "migration ticket|confirm an ETA", mention: "you"),
        m("c3", "c3-09", "Riley Morgan", 128, "ETA is the 12th, will update the ticket.", false, "ETA is the 12th", own: true),
        m("c3", "c3-10", "Joanna Wright", 100, "good morning all ☀️", false, "good morning all"),
        m("c3", "c3-11", "Declan Murphy", 96, "anyone around? need a rubber duck for 5 min", false, "rubber duck"),
        m("c3", "c3-12", "Ingrid Solberg", 80, "@everyone heads up: the Tessellate CI runners will be down Saturday 02:00 to 06:00 UTC for maintenance, plan long builds accordingly.", true, "Tessellate CI|CI runners", mention: "everyone"),
        m("c3", "c3-13", "Joanna Wright", 60, "Note the Vantage secrets rotation is due by Friday, teams that miss it get their deploy keys revoked.", true, "Vantage secrets|secrets rotation"),
        m("c3", "c3-14", "Declan Murphy", 58, "what is the wifi password for the 4th floor lol", false, "wifi password"),
        m("c3", "c3-15", "Ingrid Solberg", 45, "Snacks! there are leftover bagels in the kitchen", false, "leftover bagels"),
        m("c3", "c3-16", "Joanna Wright", 40, "Happy Friday everyone! Have a great weekend 🎉", false, "happy friday"),
        m("c3", "c3-17", "Chris Mackey", 35, "Riley, we hit a blocker on the Nimbus gateway: do you know whether the staging certs were reissued? Can not proceed without them.", true, "Nimbus gateway|staging certs"),
        m("c3", "c3-18", "Riley Morgan", 30, "Not sure, will ask the platform team.", false, "ask the platform", own: true),
        m("c3", "c3-19", "Ingrid Solberg", 22, "@Riley Morgan Cobalt exceptions list needs your team's names by end of day tomorrow.", true, "exceptions list", mention: "you"),
        m("c3", "c3-20", "Declan Murphy", 15, "@everyone free cake in the kitchen, come grab a slice before it is gone 🍰", false, "free cake|slice", mention: "everyone"),
        m("c3", "c3-21", "Chris Mackey", 9, "Heads up that the Basalt cache review is now closing early, feedback by tomorrow noon instead.", true, "closing early|feedback by tomorrow"),
        m("c3", "c3-22", "Joanna Wright", 5, "thx!", false, "thx"),
        m("c3", "c3-23", "Ingrid Solberg", 2, "Postponed: guild retro is cancelled this sprint, we will fold it into the Tessellate review next week.", true, "guild retro"),
        m("c3", "c3-24", "Ingrid Solberg", 500, "Please file your Halcyon expense reports by the 20th.", true, "Halcyon expense"),

        // ---- c4 Office Social ----
        m("c4", "c4-01", "Tara Quinn", 330, "Who is up for karaoke Friday? I will book the room", false, "karaoke"),
        m("c4", "c4-02", "Nate Ellison", 329, "count me in! 🎤", false, "count me in"),
        m("c4", "c4-03", "Tara Quinn", 400, "@everyone Office closed on the 25th for the holiday, remember to move your deliveries.", true, "office closed|move your deliveries", mention: "everyone"),
        m("c4", "c4-04", "Nate Ellison", 220, "Ordering sushi for the floor, drop your rolls in the sheet: https://example.com/sheets/sushi", false, "sushi"),
        m("c4", "c4-05", "Tara Quinn", 219, "Salmon avocado for me!", false, "salmon avocado"),
        m("c4", "c4-06", "Greta Hoffmann", 180, "@Riley Morgan many happy returns!! 🎂", false, "many happy returns", mention: "you"),
        m("c4", "c4-07", "Nate Ellison", 175, "Happy birthday Riley!!! 🎉🎉", false, "happy birthday"),
        m("c4", "c4-08", "Riley Morgan", 170, "Thank you all, cake is on me Thursday", false, "cake is on me", own: true),
        m("c4", "c4-09", "Greta Hoffmann", 120, "Anyone want to do a quick coffee run right now?", false, "coffee run"),
        m("c4", "c4-10", "Tara Quinn", 96, "Weekend hike Saturday, meet at the trailhead at 8, bring water", false, "weekend hike|trailhead"),
        m("c4", "c4-11", "Nate Ellison", 90, "lol that dog photo", false, "dog photo"),
        m("c4", "c4-12", "Greta Hoffmann", 72, "@everyone Fire drill Wednesday 10:30 sharp, please leave via the north stairwell and gather at the parking lot.", true, "fire drill", mention: "everyone"),
        m("c4", "c4-13", "Tara Quinn", 60, "Thursday pizza social is actually the mandatory security awareness session, attendance is logged.", true, "pizza social|attendance is logged"),
        m("c4", "c4-14", "Nate Ellison", 48, "😂", false, "crying laughing"),
        m("c4", "c4-15", "Greta Hoffmann", 40, "thanks for the help earlier!", false, "thanks for the help"),
        m("c4", "c4-16", "Tara Quinn", 30, "Muffins in the break room, first come first served", false, "muffins"),
        m("c4", "c4-17", "Riley Morgan", 24, "On my way for a muffin", false, "on my way", own: true),
        m("c4", "c4-18", "Greta Hoffmann", 12, "The parking garage will be closed Friday for resurfacing, use the overflow lot on Pine Street instead.", true, "parking garage|resurfacing"),
        m("c4", "c4-19", "Nate Ellison", 6, "Who took my umbrella?? 😅", false, "umbrella"),
        m("c4", "c4-20", "Tara Quinn", 2, "@Riley Morgan the visitor badge for your Thursday guest needs to be registered at reception by tomorrow 3pm.", true, "visitor badge", mention: "you"),
        m("c4", "c4-21", "Nate Ellison", 360, "Pancake breakfast in the kitchen, first come first served!", false, "pancake breakfast"),

        // ---- c5 Incident: Ledgerflow Degradation ----
        m("c5", "c5-01", "Lars Petersen", 500, "Postmortem for the Dunmore outage is due to leadership by the 5th.", true, "Dunmore outage"),
        m("c5", "c5-02", "Kevin Hayes", 50, "SEV2 declared: Ledgerflow payment queue latency above 30s, incident commander is Kevin Hayes.", true, "SEV2|payment queue"),
        m("c5", "c5-03", "Lars Petersen", 49, "@Riley Morgan you are on point for the Ledgerflow database side, please join the bridge at https://example.com/bridge/ledger", true, "database side|join the bridge", mention: "you"),
        m("c5", "c5-04", "Riley Morgan", 48, "Joining now", false, "joining now", own: true),
        m("c5", "c5-05", "Kevin Hayes", 47, "Root cause candidate: Sparrow connection pool exhausted after the 14:10 deploy.", true, "Sparrow connection pool"),
        m("c5", "c5-06", "Kevin Hayes", 46, "Rolling back the 14:10 deploy, ETA 15 minutes.", true, "rolling back"),
        m("c5", "c5-07", "Lars Petersen", 45, "coffee for the war room? I am ordering from the cafe downstairs", false, "war room|cafe downstairs"),
        m("c5", "c5-08", "Dana Ferris", 44, "Latte for me thanks", false, "latte"),
        m("c5", "c5-09", "Kevin Hayes", 40, "Update: rollback complete, latency back to normal (p99 900ms), monitoring for 30 min.", true, "rollback complete|p99"),
        m("c5", "c5-10", "Kevin Hayes", 38, "@everyone Ledgerflow incident resolved as of 15:42. No customer action needed.", true, "incident resolved", mention: "everyone"),
        m("c5", "c5-11", "Dana Ferris", 37, "Phew, nice work everyone 👏", false, "nice work everyone"),
        m("c5", "c5-12", "Lars Petersen", 30, "Follow-up: postmortem for the Ledgerflow queue incident is due Friday, Riley owns the timeline section.", true, "postmortem for the Ledgerflow|timeline section"),
        m("c5", "c5-13", "Kevin Hayes", 26, "Action item: add a pool-size alert for Sparrow before next release (owner: Dana).", true, "pool-size alert"),
        m("c5", "c5-14", "Dana Ferris", 20, "On it. Also the vendor status page lists a Marigold CDN blip at the same time, may be unrelated.", true, "Marigold CDN"),
        m("c5", "c5-15", "Kevin Hayes", 14, "@Riley Morgan can you attach the slow query log to the postmortem doc? https://example.com/docs/ledger-postmortem", true, "slow query log", mention: "you"),
        m("c5", "c5-16", "Lars Petersen", 10, "Anyone up for a beer after this week? 🍻", false, "beer"),
        m("c5", "c5-17", "Dana Ferris", 8, "sure!", false, "sure"),
        m("c5", "c5-18", "Kevin Hayes", 4, "Reminder: on-call handoff is Monday 9am, Riley takes primary from Dana.", true, "on-call handoff"),
        m("c5", "c5-19", "Lars Petersen", 3, "Is the status page still showing the degraded banner? Customers are asking.", true, "degraded banner"),
        m("c5", "c5-20", "Lars Petersen", 700, "@Riley Morgan you were listed for the Ironbridge tabletop exercise, confirm by the 2nd.", true, "Ironbridge tabletop", mention: "you"),
        m("c5", "c5-21", "Dana Ferris", 1, "ty!", false, "ty"),

        // ---- c6 Quillfeather Migration (LONG thread, 0-13 days) ----
        m("c6", "c6-01", "Katie O'Connor", 312, "Kicking off Quillfeather, our biggest infrastructure project this half: the goal is to move tenant sync from the old Marlowe queue onto the new Brackenridge pipeline before the Q4 freeze on the 28th.", true, "Brackenridge pipeline|Q4 freeze"),
        m("c6", "c6-02", "Ian Sullivan", 311, "Scoping note: the Marlowe queue has 14 consumers and three of them are undocumented. I will inventory them and post a table by Friday so we know exactly what breaks when we switch. Please flag anything you know about.", true, "table by Friday|14 consumers"),
        m("c6", "c6-03", "Petra Nilsson", 310, "Morning all, coffee is on the 3rd floor if anyone needs it", false, "3rd floor"),
        m("c6", "c6-04", "Lukas Brandt", 308, "Ran the first Quillfeather load test against the Thistledown sandbox: 4.2k msgs/sec sustained, then the broker starts dropping acks.", true, "Thistledown sandbox|4.2k"),
        m("c6", "c6-05", "Mia Thompson", 306, "Dropped acks smell like the prefetch limit. Try setting prefetch to 200 for the Alderwood consumer group and rerun the test.", true, "Alderwood consumer"),
        m("c6", "c6-06", "Lukas Brandt", 300, "Prefetch at 200 fixed the ack drops, sustained 9k msgs/sec now. Posting the full results in the wiki tonight so the rest of the team can compare against their own numbers.", true, "9k msgs"),
        m("c6", "c6-07", "Katie O'Connor", 296, "Great. Decision: Quillfeather phase 1 covers tenant sync only, and billing events wait for phase 2 in November.", true, "tenant sync only|billing events wait"),
        m("c6", "c6-08", "Erik Johansson", 290, "Thanks Katie 👍", false, "thanks katie"),
        m("c6", "c6-09", "Ian Sullivan", 284, "Inventory done: the three undocumented consumers belong to Rhubarb reporting, Onyx audit, and a dead Peregrine script we can delete.", true, "Rhubarb reporting|Onyx audit|Peregrine script"),
        m("c6", "c6-10", "Nora Halvorsen", 280, "who is ordering lunch? I am getting a chicken caesar wrap from the deli", false, "caesar wrap"),
        m("c6", "c6-11", "Petra Nilsson", 279, "Make that two for me", false, "two for me"),
        m("c6", "c6-12", "Lukas Brandt", 270, "Question for the group: do we keep the Larchmont schema versioning or switch to the flat Cinder format? I need an answer before I build the adapter.", true, "Larchmont schema|Cinder format"),
        m("c6", "c6-13", "Mia Thompson", 268, "Flat Cinder is simpler but breaks the Sable analytics consumers. I would keep Larchmont for phase 1 and revisit later.", true, "Cinder is simpler"),
        m("c6", "c6-14", "Katie O'Connor", 265, "Agreed, Larchmont stays. Lukas go ahead and build the adapter, no further discussion needed, we are behind already and cannot afford another round of debate on this.", true, "Larchmont stays"),
        m("c6", "c6-15", "Ian Sullivan", 250, "Heads up, my daughter has a school recital on Thursday so I am out from 3pm.", false, "recital"),
        m("c6", "c6-16", "Erik Johansson", 244, "The Kingfisher config repo now has branch protection, so PRs need two approvals starting this sprint. Plan reviews accordingly and ask early, since approvers are spread across three time zones.", true, "Kingfisher config"),
        m("c6", "c6-17", "Katie O'Connor", 240, "@Riley Morgan can you review the Quillfeather rollback plan draft at https://example.com/docs/rollback-plan? I need it signed off by the 12th.", true, "rollback plan draft|signed off by the 12th", mention: "you"),
        m("c6", "c6-18", "Riley Morgan", 238, "Will read it tomorrow morning.", false, "read it tomorrow morning", own: true),
        m("c6", "c6-19", "Nora Halvorsen", 230, "Pasta bake in the oven room, help yourselves", false, "pasta bake"),
        m("c6", "c6-20", "Lukas Brandt", 222, "Adapter merged. One catch: it silently drops events with null tenant ids, so I am adding a dead-letter topic called Hollyhock.", true, "Hollyhock|null tenant ids"),
        m("c6", "c6-21", "Mia Thompson", 216, "Good catch. Who reads the dead-letter topic? Someone needs to own triage or it just fills up and nobody notices for weeks until a customer complains about missing data.", true, "own triage|fills up"),
        m("c6", "c6-22", "Katie O'Connor", 210, "Riley, can your team own that triage? A weekly sweep is fine for phase 1, we can automate it afterwards once we know what kinds of events actually land there in practice.", true, "weekly sweep"),
        m("c6", "c6-23", "Riley Morgan", 209, "Yes, my team can own it, starting next sprint.", false, "starting next sprint", own: true),
        m("c6", "c6-24", "Petra Nilsson", 200, "Thanks Riley!", false, "thanks riley"),
        m("c6", "c6-25", "Erik Johansson", 190, "Alert: the Wolfram staging broker ran out of disk overnight, I purged old segments and it is stable again for now.", true, "Wolfram staging|purged old segments"),
        m("c6", "c6-26", "Ian Sullivan", 180, "Draft of the Quillfeather cutover timeline is in https://example.com/docs/cutover-timeline. Big rocks: dual write on the 3rd, read cutover on the 10th, decommission on the 24th.", true, "cutover timeline|decommission on the 24th"),
        m("c6", "c6-27", "Nora Halvorsen", 176, "Reminder: cake for Ian's promotion at 3pm in the kitchen 🎂", false, "promotion"),
        m("c6", "c6-28", "Mia Thompson", 170, "The dual write date collides with the Fenwick maintenance window, can we shift it by one day so we are not fighting the vendor for capacity during the busiest window of the month?", true, "Fenwick maintenance"),
        m("c6", "c6-29", "Katie O'Connor", 168, "Shifting dual write to the 4th. I updated the shared doc, everyone please re-read the dates and tell me today if your own plans collide with any of them.", true, "to the 4th"),
        m("c6", "c6-30", "Lukas Brandt", 160, "lol the coffee machine on 2 is dead again, anyone got a working one?", false, "coffee machine"),
        m("c6", "c6-31", "Erik Johansson", 150, "Review status: 3 open PRs on the Kingfisher side, two of them are waiting on Mia's schema sign-off before they can merge, and the third depends on those two so it will wait as well.", true, "3 open PRs"),
        m("c6", "c6-32", "Mia Thompson", 148, "Signed off the schema, sorry for the delay. The remaining two PRs should be unblocked now.", true, "signed off the schema|sorry for the delay"),
        m("c6", "c6-33", "Petra Nilsson", 140, "@everyone Quillfeather status review moved to Tuesday 11:00, room link https://example.com/rooms/quill-status", true, "status review moved|quill-status", mention: "everyone"),
        m("c6", "c6-34", "Ian Sullivan", 130, "Tuesday works for me.", false, "Tuesday works"),
        m("c6", "c6-35", "Nora Halvorsen", 125, "Anyone free right now to pair on the Bramble load harness? I am stuck.", false, "Bramble load harness|pair on"),
        m("c6", "c6-36", "Lukas Brandt", 120, "Never mind, figured out the harness thing myself, it was a stale env var.", false, "stale env var"),
        m("c6", "c6-37", "Katie O'Connor", 110, "Risk flagged: the Foxglove auth service can not handle the dual-write load, they need to scale before the 4th or we slip a week.", true, "Foxglove auth"),
        m("c6", "c6-38", "Erik Johansson", 108, "Is anyone talking to the Foxglove owners? Otherwise we are stuck waiting on their capacity plan, and the plan is not written down anywhere I can find.", true, "Foxglove owners"),
        m("c6", "c6-39", "Riley Morgan", 106, "I will talk to Sigrid Falk, she runs that service.", false, "Sigrid Falk", own: true),
        m("c6", "c6-40", "Mia Thompson", 100, "Great, thank you Riley", false, "thank you riley"),
        m("c6", "c6-41", "Katie O'Connor", 96, "@Riley Morgan I need the Quillfeather rollback plan signed off by Thursday, not the 12th, because the leadership review got pulled forward.", true, "pulled forward|leadership review", mention: "you"),
        m("c6", "c6-42", "Riley Morgan", 90, "Understood, I will get the plan reviewed by Wednesday night.", false, "reviewed by Wednesday night", own: true),
        m("c6", "c6-43", "Petra Nilsson", 84, "Someone left a blue jacket in the meeting room 2B", false, "blue jacket"),
        m("c6", "c6-44", "Lukas Brandt", 80, "Cutover rehearsal on staging: the read path works, but the write path failed on tenant ids with unicode. Filing bug QF-212.", true, "cutover rehearsal|write path failed"),
        m("c6", "c6-45", "Ian Sullivan", 76, "QF-212 root cause: the normalizer strips combining marks from ids. Patch is up at https://example.com/pr/212 for review.", true, "normalizer|combining marks"),
        m("c6", "c6-46", "Nora Halvorsen", 72, "Nice one Ian 🙌", false, "nice one ian"),
        m("c6", "c6-47", "Katie O'Connor", 70, "Decision: we freeze the Quillfeather schema on Friday. Any change after that needs my approval and a written reason.", true, "schema on Friday|written reason"),
        m("c6", "c6-48", "Erik Johansson", 66, "Question: does the freeze cover the Sable analytics consumers or only the producers?", true, "freeze cover|only the producers"),
        m("c6", "c6-49", "Katie O'Connor", 64, "Only producers. Consumers can keep changing until the read cutover happens.", true, "consumers can keep"),
        m("c6", "c6-50", "Mia Thompson", 60, "The Ashgrove dashboard still reads from the old Marlowe queue. Who owns it? Its owner never replied to my emails.", true, "Ashgrove dashboard"),
        m("c6", "c6-51", "Lukas Brandt", 58, "That one belongs to reporting, I will ping Greta Vogel there and ask her to reply to Mia.", true, "Greta Vogel"),
        m("c6", "c6-52", "Petra Nilsson", 55, "Lunch train at 12:30? Burgers at the pub, I will take orders", false, "burgers|lunch train"),
        m("c6", "c6-53", "Nora Halvorsen", 54, "Veggie burger for me", false, "veggie burger"),
        m("c6", "c6-54", "Ian Sullivan", 50, "@Riley Morgan the Quillfeather rollback plan is on the leadership agenda tomorrow 10am, can you present the rollback slide?", true, "rollback slide|leadership agenda", mention: "you"),
        m("c6", "c6-55", "Riley Morgan", 48, "Yes, I will present.", false, "I will present", own: true),
        m("c6", "c6-56", "Erik Johansson", 46, "Kingfisher branch protection is now blocking my hotfix, can someone with admin approve https://example.com/pr/230?", true, "blocking my hotfix"),
        m("c6", "c6-57", "Petra Nilsson", 44, "Approved", false, "approved"),
        m("c6", "c6-58", "Mia Thompson", 42, "happy friday eve!", false, "friday eve"),
        m("c6", "c6-59", "Katie O'Connor", 40, "Reminder: the incident-response tabletop for Quillfeather is Thursday 2pm, attendance is mandatory for all owners.", true, "tabletop|attendance is mandatory"),
        m("c6", "c6-60", "Lukas Brandt", 36, "The dead-letter topic got 300 events overnight, all from one misconfigured tenant (Orchard). Their admin needs to fix the payload.", true, "300 events|Orchard tenant"),
        m("c6", "c6-61", "Riley Morgan", 34, "Triage picked it up, opened a ticket with the tenant.", false, "opened a ticket", own: true),
        m("c6", "c6-62", "Ian Sullivan", 30, "Nice. Also FYI the Quillfeather wiki space is being archived on the 30th, so export anything you need before then, including screenshots, benchmark tables and the old diagrams.", true, "wiki space|archived on the 30th"),
        m("c6", "c6-63", "Nora Halvorsen", 28, "Anyone want to join the running club tomorrow at 7? 🏃", false, "running club"),
        m("c6", "c6-64", "Erik Johansson", 27, "I'm in!", false, "I'm in"),
        m("c6", "c6-65", "Katie O'Connor", 26, "@Riley Morgan quick sync tomorrow 9am to review the rollback drill results before leadership? I will send an invite.", true, "sync tomorrow 9am", mention: "you"),
        m("c6", "c6-66", "Lukas Brandt", 25, "Rollback drill result: full restore in 11 minutes, under the 15 minute target we set for phase 1.", true, "restore in 11 minutes|15 minute target"),
        m("c6", "c6-67", "Mia Thompson", 24, "Reads great. One gap: the Cinder exporter has no retry on 503s, so it will lose events during Foxglove restarts.", true, "Cinder exporter|retry on 503s"),
        m("c6", "c6-68", "Lukas Brandt", 22, "Adding exponential retry to the exporter, should be done by end of day and I will post the PR here.", true, "exponential retry"),
        m("c6", "c6-69", "Petra Nilsson", 21, "Sushi for lunch? ordering from the place on Elm at 12", false, "sushi|place on Elm"),
        m("c6", "c6-70", "Nora Halvorsen", 20, "Salmon nigiri x3", false, "salmon nigiri"),
        m("c6", "c6-71", "Katie O'Connor", 18, "@everyone final go/no-go for phase 1 is Wednesday 15:00, please have your readiness checklists filled in at https://example.com/docs/readiness before then.", true, "go/no-go|readiness checklists", mention: "everyone"),
        m("c6", "c6-72", "Erik Johansson", 16, "🙏🙏", false, "folded hands"),
        m("c6", "c6-73", "Ian Sullivan", 14, "Blocker: the misconfigured tenant still fails signature checks, so we can not close the bug bash without their fix. Any idea who signs their certs?", true, "signature checks|signs their certs"),
        m("c6", "c6-74", "Lukas Brandt", 12, "@Riley Morgan your triage rota starts Monday, first shift is yours. Runbook is at https://example.com/docs/triage-runbook.", true, "triage rota|triage-runbook", mention: "you"),
        m("c6", "c6-75", "Mia Thompson", 11, "Weekend plans anyone? Going to the coast 🌊", false, "coast"),
        m("c6", "c6-76", "Nora Halvorsen", 10, "Nothing planned, probably laundry lol", false, "laundry"),
        m("c6", "c6-77", "Katie O'Connor", 9, "Decision on the bad tenant: we notify them formally and give them until Friday to fix it, otherwise we quarantine their data feed until they confirm the fix in writing.", true, "quarantine|notify them formally"),
        m("c6", "c6-78", "Petra Nilsson", 8, "Coffee chat about the Quillfeather roadmap? jk, just coffee at 3", false, "just coffee at 3|coffee chat"),
        m("c6", "c6-79", "Erik Johansson", 7, "The Marlowe queue decommission ticket is open, targeted for the 24th, and it needs a named owner by end of week.", true, "decommission ticket|named owner"),
        m("c6", "c6-80", "Ian Sullivan", 6, "Volunteering Lukas as the owner since he built the adapter and knows the consumers best, and he already offered to keep a short handover note for the rota.", true, "volunteering Lukas"),
        m("c6", "c6-81", "Lukas Brandt", 5, "Fine by me 😄", false, "fine by me"),
        m("c6", "c6-82", "Katie O'Connor", 4, "The dashboard owner finally replied: they can migrate on the 9th but need the new topic names beforehand, so someone please send them today, because their migration window is tight and they have no slack.", true, "migrate on the 9th"),
        m("c6", "c6-83", "Nora Halvorsen", 3, "Anyone seen my charger? white USB-C, left it in room 2B", false, "charger"),
        m("c6", "c6-84", "Mia Thompson", 2, "Sending the topic names now, they are in https://example.com/docs/topic-names for the dashboard team.", true, "topic-names"),
        m("c6", "c6-85", "Riley Morgan", 1, "Thanks Mia", false, "thanks mia", own: true),
        m("c6", "c6-86", "Ian Sullivan", 205, "Proposal: run the Quillfeather dual-write in shadow mode for 48 hours first, compare row counts nightly, then flip. Objections by Monday please.", true, "shadow mode|row counts"),
        m("c6", "c6-87", "Mia Thompson", 195, "No objection from me, but I want the Saltmarsh reconciliation report attached to each nightly comparison so we can audit drift.", true, "Saltmarsh reconciliation"),
        m("c6", "c6-88", "Katie O'Connor", 185, "Go ahead, we will do the 48 hour trial with the reconciliation report attached every night before the flip.", true, "48 hour trial"),
        m("c6", "c6-89", "Petra Nilsson", 155, "Vendor sent the Harrowgate SDK v2, the changelog mentions a breaking change to token refresh at https://example.com/docs/harrowgate-changelog.", true, "Harrowgate SDK|harrowgate-changelog"),
        m("c6", "c6-90", "Lukas Brandt", 135, "Token refresh breaking change confirmed, so we need to pin Harrowgate to v1.9 until phase 2 lands.", true, "pin Harrowgate|v1.9"),
        m("c6", "c6-91", "Nora Halvorsen", 115, "Just so everyone knows, the printer on 3 is out of toner again", false, "printer on 3|toner"),
        m("c6", "c6-92", "Erik Johansson", 105, "Load test at 2x peak on Thursday night, staging will be unavailable from 20:00 to 23:00 so do not schedule anything there, including the overnight batch jobs that normally run around 21:00.", true, "2x peak|unavailable from 20:00"),
        m("c6", "c6-93", "Ian Sullivan", 88, "Tiny one: anyone got a spare HDMI cable? 🙏", false, "HDMI"),
        m("c6", "c6-94", "Katie O'Connor", 78, "Note the Quillfeather budget review is next Monday, I need everyone's contractor hours by Friday EOD.", true, "budget review|contractor hours"),
        m("c6", "c6-95", "Lukas Brandt", 37, "Report from last night's shadow comparison: 0.02 percent row-count drift, all in one bad tenant. Full CSV at https://example.com/reports/drift.csv", true, "shadow comparison|drift.csv"),
        m("c6", "c6-96", "Mia Thompson", 15, "Read it, the drift matches the misconfigured tenant, no new bugs 👍", false, "no new bugs"),
    ]
}
